INSERT INTO shop_item_type (item_type_id, name, description) VALUES
    (1, 'Maske za lice', 'Maske za lice'),
    (2, 'Medicinske maske', 'Medicinske maske'),
    (3, 'Filtrirajuće polumaske', 'Filtrirajuće polumaske'),
    (4, 'Dezinfikacijska sredstva', 'Dezinfikacijska sredstva'),
    (5, 'Zaštitni viziri', 'Zaštitni viziri'),
    (6, 'Zaštitne rukavice', 'Zaštitne rukavice');

INSERT INTO shop_item (item_id, name, description, type, amount, cost, discount, image) VALUES
    (1, 'Maska za lice', '3-slojna maska za jednokratnu upotrebu koja štiti druge osobe od respiratornih kapljica osobe koja nosi masku. Za optimalnu učinkovitost dvoslojnu pamučnu tekstilnu masku ​​za lice, koja ima ulogu tekstilne barijere, treba pravilno nositi (tj. staviti je da čvrsto prianja na nos i usta), mijenjati je ako je mokra i ne dirati je dok se nosi.', 1, 1500, 5.00, 0.0, 'https://birodom.hr/upload/catalog/product/3987/55565-maska-za-lice-medicinska-troslojna-s-gumicom_5f18301e04877.jpg'),
    (2, 'Paket maski za lice 50/1', 'Paket od 50 troslojnih maski za lice.', 1, 1500, 200.00, 10.0, 'https://paperstar.ba/shop/wp-content/uploads/2020/11/maske.jpg'),
    (3, 'Medicinska maska', 'Koriste se prvenstveno u medicinske svrhe i služe za sprječavanje širenja kapljica iz izdahnutog zraka na pacijenta ili drugu osobu te mogu zaštititi područje usta i nosa od direktnog utjecaja većih kapljica druge osobe kao i od prijenosa patogena izravnim dodirom s rukama.', 2, 1500, 7.00, 0.0, 'https://5.imimg.com/data5/DU/FW/UG/SELLER-48535299/face-mask-2-ply-green-with-tie-500x500.jpeg'),
    (4, 'Paket medicinskih maski 50/1', 'Paket od 50 medicinskih masaka.', 2, 1500, 300.00, 10.0, 'https://www.makromikrogrupa.hr/Documents/Products/13064/180707343_san_maska_medicinska_tip_iir_troslojna_-_pakiranje_50_komada_2.jpg'),
    (5, 'Filtrirajuće polumaske bez ventilom(FFP2)', 'Filtrirajuće polumaske (FFP) ubrajaju se u osobnu zaštitnu opremu (OZO) u kontekstu zaštite na radu i namijenjene su zaštiti od čestica, kapljica i aerosola u zdravstveni ustanovama. Njihova primjena je jednokratna. Postoje maske bez ventila za izdah i maske s ventilom za izdah. Ova je bez ventila za izdah, one filtriraju udisani zrak i izdisani zrak i zato osiguravaju i samozaštitu i vanjsku zaštitu.', 3, 1500, 10.00, 0.0, 'https://birodom.hr/upload/catalog/product/4257/thumb/55615-5-maska-20tastitna-za-lice-bez-20ventila-20k_5f8ffa3628306_550x550r.jpg'),
    (6, 'Filtrirajuće polumaske s ventilom(FFP3)', 'Filtrirajuće polumaske (FFP) ubrajaju se u osobnu zaštitnu opremu (OZO) u kontekstu zaštite na radu i namijenjene su zaštiti od čestica, kapljica i aerosola u zdravstveni ustanovama. Njihova primjena je jednokratna. Postoje maske bez ventila za izdah i maske s ventilom za izdah. Ova je s ventilom za izdah, one filtriraju samo udahnuti zrak i stoga osiguravaju samozaštitu.', 3, 1500, 15.00, 0.0, 'https://www.zutiklik.hr/images/thumbs/023/0236612_zastitna-maska-za-lice-ffp3_550.jpeg'),
    (7, 'Paket filtrirajućih polumaski bez ventila za izdah(FFP2) 50/1', 'Paket od 50 filtrirajućih polumaski bez ventila za izdah.', 3, 1500, 250.00, 20.0, 'https://www.igrackeshop.hr/upload_files/products/ffp2-zastitna-maska-kn95-1kom.jpg'),
    (8, 'Paket filtrirajućih polumaski sa ventilom za izdah(FFP3) 50/1', 'Paket od 50 filtrirajućih polumaski sa ventilom za izdah.', 3, 1500, 400.00, 20.0, 'https://st3.myideasoft.com/idea/bc/15/myassets/products/424/era-6210v-1.jpg?revision=1584092868'),
    (9, 'Paket filtrirajućih polumaski bez ventila za izdah(FFP2) 500/1', 'Paket od 500 filtrirajućih polumaski bez ventila za izdah', 3, 1500, 1200, 15.0, 'https://www.igrackeshop.hr/upload_files/products/ffp2-zastitna-maska-kn95-1kom.jpg'),
    (10, 'Paket filtrirajućih polumaski sa ventilom za izdah(FFP3) 500/1', 'Paket od 500 filtrirajućih polumaski sa ventilom za izdah.', 3, 1500, 1500, 15.0, 'https://st3.myideasoft.com/idea/bc/15/myassets/products/424/era-6210v-1.jpg?revision=1584092868'),
    (11, 'Dezinfekcijsko sredstvo za ruke', 'Dezinfekcijsko sredstvo za ruke, bočica 500ml.', 4, 1500, 15.00, 0.0, 'https://cdn11.bigcommerce.com/s-2ftxiodi6b/images/stencil/1280x1280/attribute_rule_images/6980_source_1594988137.png'),
    (12, 'Paket dezinfekcijskih sredstava za ruke 50/1', 'Paket od 50 bočica po 500ml dezinfekcijskog sredstva za ruke.', 4, 1500, 250.00, 15.0, 'https://www.kingfisherdirect.co.uk/image/cache/data/robinson-healthcare/70-percent-alcohol-hand-disinfectant-spray-100ml-box-800x800.jpg'),
    (13, 'Zaštitni vizir', 'Vizir zaštitni, višekratni, dimenzije 20x30cm, podesiva širina pomoću trake i čička, na unutarnjoj strani transparentni džep za ubacivanje papirića sa imenom; materijal transparentni polivinilklor.', 5, 1500, 30.00, 0.0, 'https://ebwdistributors.com/wp-content/uploads/2020/06/face-shields-1.jpg'),
    (14, 'Paket zaštitnih vizira 20/1', 'Paket od 20 zaštitnih vizira.', 5, 1500, 350.00, 15.0, 'https://www.bdshop.com/pub/media/catalog/product/f/a/face-shield-splash-proof-face-eyes-protector-5pcs10pcs-pack.jpg'),
    (15, 'Zaštitne rukavice', 'Zaštitne rukavice koje štite ruke.', 6, 1500, 2.00, 0.0, 'https://image.made-in-china.com/226f3j00oSvTUAbdrWqG/Disposable-Latex-Free-Medical-Nitrile-Gloves.jpg'),
    (16, 'Paket zaštitnih rukavica 100/1', 'Paket od 100 zaštitnih rukavica, plave boje, jednokratna upotreba.', 6, 1500, 70.00, 0.0, 'https://hr.traconelectric.com/static/images/items/B02/B_2019/kesztyu_adatlap_watermark_portal_800x800.png'),
    (17, 'Rukavice latex s puderom vel. S', 'Zaštitne latex rukavice, vrlo su otporne na propusnost i kidanje. Imaju odličnu osjetljivost. Paket od 100 latex rukavica s puderom. Veličina S, bijela boja.', 6, 1500, 100.00, 0.0, 'https://birodom.hr/upload/catalog/product/2657/thumb/rukavice-latex_5ebbff05e7c75_550x550r.jpg' ),
    (18, 'Rukavice latex s puderom vel. M', 'Zaštitne latex rukavice, vrlo su otporne na propusnost i kidanje. Imaju odličnu osjetljivost. Paket od 100 latex rukavica s puderom. Veličina M, bijela boja.', 6, 1500, 100.00, 0.0, 'https://birodom.hr/upload/catalog/product/2657/thumb/rukavice-latex_5ebbff05e7c75_550x550r.jpg' ),
    (19, 'Rukavice latex s puderom vel. L', 'Zaštitne latex rukavice, vrlo su otporne na propusnost i kidanje. Imaju odličnu osjetljivost. Paket od 100 latex rukavica s puderom. Veličina L, bijela boja.', 6, 1500, 100.00, 0.0, 'https://birodom.hr/upload/catalog/product/2657/thumb/rukavice-latex_5ebbff05e7c75_550x550r.jpg' ),
    (20, 'Rukavice latex s puderom vel. XL', 'Zaštitne latex rukavice, vrlo su otporne na propusnost i kidanje. Imaju odličnu osjetljivost. Paket od 100 latex rukavica s puderom. Veličina XL, bijela boja.', 6, 1500, 100.00, 0.0, 'https://birodom.hr/upload/catalog/product/2657/thumb/rukavice-latex_5ebbff05e7c75_550x550r.jpg' ),
    (21, 'Rukavice latex bez pudera vel. S', 'Zaštitne latex rukavice bez pudera, vrlo su otporne na propusnost i kidanje. Imaju odličnu osjetljivost. Paket od 100 latex rukavica s puderom. Veličina S, bijela boja.', 6, 1500, 100.00, 0.0, 'https://birodom.hr/upload/catalog/product/3990/thumb/55611-rukavice-elasticnie-medicinske-bez-pudera_5f18685d4586d_550x550r.jpg' ),
    (22, 'Rukavice latex bez pudera vel. M', 'Zaštitne latex rukavice bez pudera, vrlo su otporne na propusnost i kidanje. Imaju odličnu osjetljivost. Paket od 100 latex rukavica s puderom. Veličina M, bijela boja.', 6, 1500, 100.00, 0.0, 'https://birodom.hr/upload/catalog/product/3990/thumb/55611-rukavice-elasticnie-medicinske-bez-pudera_5f18685d4586d_550x550r.jpg' ),
    (23, 'Rukavice latex bez pudera vel. L', 'Zaštitne latex rukavice bez pudera, vrlo su otporne na propusnost i kidanje. Imaju odličnu osjetljivost. Paket od 100 latex rukavica s puderom. Veličina L, bijela boja.', 6, 1500, 100.00, 0.0, 'https://birodom.hr/upload/catalog/product/3990/thumb/55611-rukavice-elasticnie-medicinske-bez-pudera_5f18685d4586d_550x550r.jpg' ),
    (24, 'Rukavice latex bez pudera vel. XL', 'Zaštitne latex rukavice bez pudera, vrlo su otporne na propusnost i kidanje. Imaju odličnu osjetljivost. Paket od 100 latex rukavica s puderom. Veličina XL, bijela boja.', 6, 1500, 100.00, 0.0, 'https://birodom.hr/upload/catalog/product/3990/thumb/55611-rukavice-elasticnie-medicinske-bez-pudera_5f18685d4586d_550x550r.jpg' ),
    (25, 'Vlažne toalet-maramice za dezinfekciju ruku', 'Dezinfekcijske maramice na bazi 70% alkohola. Brzo se suše i ne ostavljaju tragove brisanja. Higijenske maramice namijenjene su čišćenju i dezinficiranju ruku, manjih površina koje svakodenevno i često dodirujemo, poput mobitela, POS uređaja, tableta, monitora, ključeva, kvaka i sl, ali i svih ostalih ravnih površina.', 4, 1500, 1.5, 0.0, 'https://aspirationlife.com/wp-content/uploads/2020/09/ASP-RH-5028-1.jpg'),
    (26, 'Paket vlažnih toalet-maramica za dezinfekciju ruku 100/1', 'Dezinfekcijske maramice na bazi 70% alkohola. Brzo se suše i ne ostavljaju tragove brisanja. Higijenske maramice namijenjene su čišćenju i dezinficiranju ruku, manjih površina koje svakodenevno i često dodirujemo, poput mobitela, POS uređaja, tableta, monitora, ključeva, kvaka i sl, ali i svih ostalih ravnih površina. Paket: 100 vlažnih toalet-maramica', 4, 1500, 150, 0.0, 'https://www.arthy.co.uk/wp-content/uploads/2020/10/Fastaid.png'),
    (27, 'Paket vlažnih toalet-maramica za dezinfekciju ruku 500/1', 'Dezinfekcijske maramice na bazi 70% alkohola. Brzo se suše i ne ostavljaju tragove brisanja. Higijenske maramice namijenjene su čišćenju i dezinficiranju ruku, manjih površina koje svakodenevno i često dodirujemo, poput mobitela, POS uređaja, tableta, monitora, ključeva, kvaka i sl, ali i svih ostalih ravnih površina. Paket: 500 vlažnih toalet-maramica', 4, 1500, 300, 0.0, 'https://www.arthy.co.uk/wp-content/uploads/2020/10/Fastaid.png'),
    (28, 'Paket vlažnih toalet-maramica za dezinfekciju ruku 1000/1', 'Dezinfekcijske maramice na bazi 70% alkohola. Brzo se suše i ne ostavljaju tragove brisanja. Higijenske maramice namijenjene su čišćenju i dezinficiranju ruku, manjih površina koje svakodenevno i često dodirujemo, poput mobitela, POS uređaja, tableta, monitora, ključeva, kvaka i sl, ali i svih ostalih ravnih površina. Paket: 1000 vlažnih toalet-maramica', 4, 1500, 600, 0.0, 'https://www.arthy.co.uk/wp-content/uploads/2020/10/Fastaid.png'),
    (29, 'Sredstvo za dezinfekciju ruku', 'Alkoholni dezinficijens za ruke koji brzo i efikasno djeluje na gram pozitivne i grama negativne bakterije, viruse i gljivice. Nakon upotrebe koža ruku je glatka i nježna. Koristi se za dezinfekciju ruku u prehrambenoj industriji, zdravstvu, hotelsko – ugostiteljskim objektima, funkcionalnim područjima visokog rizika (operacijske dvorane, intenzivna njega...)Količina: 500ml', 4, 1500, 35, 0.0, 'https://birodom.hr/upload/catalog/product/3263/thumb/55602-sredstvo-za-dezinfekciju-ruku-labpro-dermode_5ef45f5dea46e_550x550r.jpg'),
    (30, 'Sredstvo za dezinfekciju ruku', 'Alkoholni dezinficijens za ruke koji brzo i efikasno djeluje na gram pozitivne i grama negativne bakterije, viruse i gljivice. Nakon upotrebe koža ruku je glatka i nježna. Koristi se za dezinfekciju ruku u prehrambenoj industriji, zdravstvu, hotelsko – ugostiteljskim objektima, funkcionalnim područjima visokog rizika (operacijske dvorane, intenzivna njega...)Količina: 1000ml', 4, 1500, 50, 0.0, 'https://birodom.hr/upload/catalog/product/2765/thumb/55443-sredstvo-za-dezinf-ruku-labpro-dermodez-1000_5ef5bab6c56d0_550x550r.jpg'),
    (31, 'Sredstvo za dezinfekciju ruku', 'Alkoholni dezinficijens za ruke koji brzo i efikasno djeluje na gram pozitivne i grama negativne bakterije, viruse i gljivice. Nakon upotrebe koža ruku je glatka i nježna. Koristi se za dezinfekciju ruku u prehrambenoj industriji, zdravstvu, hotelsko – ugostiteljskim objektima, funkcionalnim područjima visokog rizika (operacijske dvorane, intenzivna njega...). Količina: 5000ml', 4, 1500, 200, 0.0, 'https://birodom.hr/upload/catalog/product/2767/thumb/55444-sredstvo-za-dezinfekciju-ruku-labpro-dermode_5ec690a612a65_550x550r.jpg'),
    (32, 'Sredstvo za dezinfekciju prostora 1000ml', 'Dezinficijens s prskalicom je tekuće sredstvo za brzu dezinfekciju površina. Na bazi alkohola, nije ga potrebno razrijeđivati. Količina: 1000ml', 4, 1500, 65.00, 0.0, 'https://birodom.hr/upload/catalog/product/2535/thumb/55416-sredstvo-20za-20dezinfekciju-20prostora-20la_5ef32cea81a74_550x550r.jpg'),
    (33, 'Sredstvo za dezinfekciju prostora 5000ml', 'Dezinficijens, tekuće sredstvo za dezinfekciju površina. Na bazi alkohola, nije ga potrebno razrijeđivati. Količina: 5000ml', 4, 1500, 300.00, 0.0, 'https://birodom.hr/upload/catalog/product/2767/thumb/55444-sredstvo-za-dezinfekciju-ruku-labpro-dermode_5ec690a612a65_550x550r.jpg'),
    (34, 'Spremnik za dezinficijens za ruke beskontaktni R-3004SP', 'Beskontaktni spremnik dezinficijensa za dezinfekciju ruku na baterije. Ima 3 razine podešavanja ispuštanja dezinficijensa (3 ml, 6 ml ili 9 ml). Ovisno o razini, uređaj ispušta mlaz (3 ml) u intervalima. Preporučena razina: 1 / 3ml.Jednostavno dolijevanje. Može se montirati na zid ili na posebni stalak. Dimenzije: 65 x 75 x 230 mm, kapacitet: 1000 ml. Baterije: 6 x AA (1,5V) - baterije se ne isporučuju sa uređajem', 4, 1500, 450.00, 0.0, 'https://birodom.hr/upload/catalog/product/2780/thumb/55438-spremnik-za-dezificijens-za-ruke-beskontaktn_5f155eb616a3a_550x550r.jpg'),
    (35, 'Spremnik za dezinficijens za ruke beskontaktni stolni SA-7400', 'Beskontaktni stolni spremnik na baterije za dezinficijens. Spremnik je samostojeći, prikladan za smještaj na stolu ili nekom drugom namještaju, ali može se montirati i na zid. 3 razine podešavanja ispuštanja dezinficijensa (3 ml, 6 ml ili 9 ml). Ovisno o razini, uređaj ispušta mlaz od 3 ml u intervalima. Preporuča se uređaj podesiti na ispuštanje samo jednog mlaza. Jednostavno ulijevanje dezinficijensa. Dimenzije (šxv): 90 x 230 mm, kapacitet: 300 ml. Baterije: 3 x AA (1,5 V) baterije - ne dolaze uz spremnik', 4, 1500, 450.00, 0.0, 'https://birodom.hr/upload/catalog/product/4248/thumb/55624-spremnik-20beskontaktni-20stolni-20sa-7400-w_5f74953db5d31_550x550r.jpg'),
    (36, 'Paket maski za lice 100/1', 'Paket od 100 troslojnih maski za lice.', 1, 1500, 300.00, 10.0, 'https://paperstar.ba/shop/wp-content/uploads/2020/11/maske.jpg'),
    (37, 'Paket maski za lice 500/1', 'Paket od 500 troslojnih maski za lice.', 1, 1500, 400.00, 10.0, 'https://paperstar.ba/shop/wp-content/uploads/2020/11/maske.jpg'),
    (38, 'Paket maski za lice 1000/1', 'Paket od 1000 troslojnih maski za lice.', 1, 1500, 500.00, 10.0, 'https://paperstar.ba/shop/wp-content/uploads/2020/11/maske.jpg'),
    (39, 'Paket medicinskih maski 100/1', 'Paket od 100 medicinskih masaka.', 2, 1500, 400.00, 10.0, 'https://images-na.ssl-images-amazon.com/images/I/71VvOjjiSWL._SL1410_.jpg'),
    (40, 'Paket medicinskih maski 500/1', 'Paket od 500 medicinskih masaka.', 2, 1500, 500.00, 10.0, 'https://images-na.ssl-images-amazon.com/images/I/71VvOjjiSWL._SL1410_.jpg'),
    (41, 'Paket medicinskih maski 1000/1', 'Paket od 1000 medicinskih masaka.', 2, 1500, 700.00, 10.0, 'https://images-na.ssl-images-amazon.com/images/I/71VvOjjiSWL._SL1410_.jpg'),
    (42, 'Paket zaštitnih vizira 50/1', 'Paket od 50 zaštitnih vizira.', 5, 1500, 500.00, 15.0, 'https://www.bdshop.com/pub/media/catalog/product/f/a/face-shield-splash-proof-face-eyes-protector-5pcs10pcs-pack.jpg'),
    (43, 'Paket zaštitnih vizira 100/1', 'Paket od 100 zaštitnih vizira.', 5, 1500, 750.00, 15.0, 'https://www.bdshop.com/pub/media/catalog/product/f/a/face-shield-splash-proof-face-eyes-protector-5pcs10pcs-pack.jpg'),
    (44, 'Paket zaštitnih vizira 200/1', 'Paket od 200 zaštitnih vizira.', 5, 1500, 1000.00, 15.0, 'https://www.bdshop.com/pub/media/catalog/product/f/a/face-shield-splash-proof-face-eyes-protector-5pcs10pcs-pack.jpg');


INSERT INTO shop_order_status_type (status_id, name, description) VALUES
    (0, 'Cart', 'Cart'),
    (1, 'Initiated', 'Customer has paid for the items in their cart'),
    (2, 'Processing', 'Vendor is in process of delivering the items'),
    (3, 'Delivered', 'Vendor has delivered the items to the customer');

INSERT INTO shop_user_card_type (type_id, name, regex, image) VALUES
    (0, 'Unknown', '', 'https://thumbs.dreamstime.com/b/unknown-credit-card-isolated-white-background-unknown-credit-card-icon-116901050.jpg'),
    (1, 'Maestro', '^(5018|5020|5038|6304|6759|6761|6763)[0-9]{8,15}$', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Maestro_2016.svg/1200px-Maestro_2016.svg.png'),
    (2, 'MasterCard', '^(5[1-5][0-9]{14}|2(22[1-9][0-9]{12}|2[3-9][0-9]{13}|[3-6][0-9]{14}|7[0-1][0-9]{13}|720[0-9]{12}))$', 'https://www.mastercard.hr/content/dam/mccom/global/logos/logo-mastercard-mobile.svg'),
    (3, 'Visa', '^4[0-9]{12}(?:[0-9]{3})?$', 'https://alkar-adventures.com/wp-content/uploads/2020/12/visa.svg');

INSERT INTO shop_notification_template (template_id, title, content) VALUES
    (1, 'Cart item removed', '<p>Dear <strong>@username@</strong>,<br><br>we have automatically removed an item named <strong>@itemname@</strong> from your cart due to it being almost taken out of stock!<br><br>Please check out the store for the availability of item in question, and re-add it to your cart.<br><br>Thanks for understanding and best regards!</p>');